import type { Metadata } from 'next';
import { VT323 } from 'next/font/google';
import './globals.css';

const mainFont = VT323({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// If loading a variable font, you don't need to specify the font weight

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${mainFont.className}  antialiased`}>{children}</body>
    </html>
  );
}
