export const skills = {
  header: 'My skills',
  intro:
    'Sapien bibendum donec lorem, purus dui montes sodales integer. Ultrices hendrerit facilisi class enim platea. Potenti nec mus non placerat vulputate augue.',
  skills: [
    'React',
    'Vue.js',
    'Angular',
    'Svelte',
    'Next.js',
    'Gatsby',
    'Redux',
    'JavaScript',
    'TypeScript',
    'HTML5',
    'CSS3',
    'Sass',
    'LESS',
    'Tailwind CSS',
    'Bootstrap',
    'Material-UI',
    'Chakra UI',
    'Styled-components',
    'jQuery',
    'Webpack',
    'Parcel',
    'Vite',
    'Babel',
    'ESLint',
    'Prettier',
    'GraphQL',
    'REST API',
    'Axios',
    'Jest',
    'Cypress',
  ],
};
